package template

import (
	"strings"

	"github.com/yoshihiro-shu/connect-go-mpc/cmd/protoc-gen-connect-go-mpc/parser"
	"google.golang.org/protobuf/compiler/protogen"
)

// GenerateCode はMCPサーバーコードを生成します
func GenerateCode(g *protogen.GeneratedFile, pkgName string, services []parser.Service) error {
	// インポート
	g.P("// Code generated by connect-go-mpc DO NOT EDIT.")
	g.P("package ", pkgName, "connectgompc")
	g.P()

	// インポート宣言
	generateImports(g, services)
	g.P()

	// 各サービスに対するコード生成
	for _, service := range services {
		// NewMCPServerWithTools 関数
		generateServerWithTools(g, service)
		g.P()
	}

	return nil
}

// generateImports はインポート宣言を生成します
func generateImports(g *protogen.GeneratedFile, services []parser.Service) {
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"fmt"`)
	g.P()
	g.P(`	"github.com/mark3labs/mcp-go/mcp"`)
	g.P(`	"github.com/mark3labs/mcp-go/server"`)
	g.P(`	connectgompc "github.com/yoshihiro-shu/connect-go-mpc"`)
	g.P(")")
}

// generateServerWithTools はMCPサーバー初期化関数を生成します
func generateServerWithTools(g *protogen.GeneratedFile, service parser.Service) {
	g.P("// NewMCPServerWithTools は設定済みの ", service.Name, " MCP サーバーを生成して返します")
	g.P("func New", service.Name, "MCPServer(baseURL string, opts ...connectgompc.ClientOption) *server.MCPServer {")
	g.P("  server := server.NewMCPServer(\"", service.Name, "\", \"1.0.0\")")
	g.P()
	g.P("  toolHandler := connectgompc.NewToolHandler(baseURL, opts...)")

	// 各メソッドに対するツール登録
	for _, method := range service.Methods {
		toolName := method.Comment
		if toolName == "" {
			toolName = method.Name
		}

		g.P("  server.AddTool(")
		g.P(`    mcp.NewTool("`, toolName, `",`)

		// 説明
		if method.RequestComment != "" {
			g.P(`      mcp.WithDescription("`, escapeString(method.RequestComment), `"),`)
		}

		// パラメータ定義
		for _, field := range method.RequestFields {
			paramType := getParamType(field.Type)

			g.P(`      mcp.With`, paramType, `("`, field.Name, `",`)
			if field.IsRequired {
				g.P(`        mcp.Required(),`)
			}
			if field.Description != "" {
				g.P(`        mcp.Description("`, escapeString(field.Description), `"),`)
			}
			g.P(`      ),`)
		}

		g.P("    ),")
		g.P("    func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {")
		g.P("      return toolHandler.Handle(ctx, req, \"", method.Name, "\")")
		g.P("    },")
		g.P("  )")
		g.P()
	}

	g.P("  return server")
	g.P("}")
}

// getParamType はMCPパラメータ型を取得します
func getParamType(goType string) string {
	switch goType {
	case "string":
		return "String"
	case "bool":
		return "Bool"
	case "int32", "int64", "float32", "float64":
		return "Number"
	default:
		return "Object"
	}
}

// escapeString は文字列をエスケープします
func escapeString(s string) string {
	return strings.ReplaceAll(s, `"`, `\"`)
}
